<h1 align="center">Manipulación de datos con Pandas y NumPy</h1>

## U2.01 Estructuras principales.

###	Series en pandas

Una Serie es una columna individual con un índice asociado. Es como una lista mejorada con etiquetas.

In [2]:
import pandas as pd

In [7]:
ventas_diarias =pd.Series([1200, 1500, 980, 2100, 1750])
ventas_diarias + 100

0    1300
1    1600
2    1080
3    2200
4    1850
dtype: int64

###	DataFrame en pandas

Un DataFrame es una tabla completa formada por múltiples Series (columnas).

In [8]:
df=pd.read_csv('ventas_completas.csv')
df.columns

Index(['id_venta', 'fecha', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'subtotal', 'descuento_porcentaje',
       'monto_descuento', 'total', 'region', 'vendedor', 'estado'],
      dtype='str')

In [9]:
filas, columnas = df.shape
print(f'El DataFrame tiene {filas} filas y {columnas} columnas')

El DataFrame tiene 500 filas y 13 columnas

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_venta              500 non-null    int64
 1   fecha                 500 non-null    str
 2   producto              500 non-null    str
 3   categoria             500 non-null    str
 4   cantidad              500 non-null    int64
 5   precio_unitario       500 non-null    float64
 6   subtotal              500 non-null    float64
 7   descuento_porcentaje  500 non-null    float64
 8   monto_descuento       500 non-null    float64
 9   total                 500 non-null    float64
 10  region                500 non-null    str
 11  vendedor              500 non-null    str
 12  estado                500 non-null    str
dtypes: float64(5), int64(2), str(6)
memory usage: 50.9 KB

### Relación entre Serie y DataFrame diferencias y uso.

In [11]:
type(df)

pandas.DataFrame

In [12]:
type(df['fecha'])

pandas.Series

In [13]:
type(df[['fecha']])

pandas.DataFrame

In [15]:
type(df[['fecha']])

pandas.DataFrame

In [17]:
dfnuevo = df[['total']]
dfnuevo['total con iva'] = dfnuevo[['total']] * 1.19
dfnuevo.head()

      total  total con iva
0  13090.68     15577.9092
1   1070.65      1274.0735
2    477.56       568.2964
3    313.80       373.4220
4    155.22       184.7118

¿Cuándo usar cada estructura?

| Estructura | Cuándo usar                                                            |
| ---------- | ---------------------------------------------------------------------- |
| Serie      | Trabajar con una columna individual, aplicar operaciones a un campo    |
| DataFrame  | Manipulación de datos tabulares completos                              |

## U2.02  - Selección y filtrado

### Selección de columnas (por nombre, por lista)

In [3]:
import pandas as pd
df = pd.read_csv('ventas_completas.csv')
print(list(df.columns))

['id_venta', 'fecha', 'producto', 'categoria', 'cantidad', 'precio_unitario', 'subtotal', 'descuento_porcentaje', 'monto_descuento', 'total', 'region', 'vendedor', 'estado']

In [4]:
df_sleccionado=df[['producto', 'total', 'cantidad']]
df_sleccionado.head()

                producto     total  cantidad
0        Laptop Dell XPS  13090.68        12
1        Laptop Dell XPS   1070.65         1
2          Disco SSD 1TB    477.56         4
3  Auriculares Bluetooth    313.80         5
4         Mouse Logitech    155.22         6

In [5]:
columnas_numericas = df.select_dtypes(include='number')
columnas_numericas

,id_venta,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total
0,2000,12,1173.00,14076.00,0.07,985.32,13090.68
1,2001,1,1151.24,1151.24,0.07,80.59,1070.65
2,2002,4,119.39,477.56,0.00,0.00,477.56
3,2003,5,62.76,313.80,0.00,0.00,313.80
4,2004,6,25.87,155.22,0.00,0.00,155.22
...,...,...,...,...,...,...,...
495,2495,5,46.54,232.70,0.00,0.00,232.70
496,2496,13,77.44,1006.72,0.08,80.54,926.18
497,2497,4,78.10,312.40,0.00,0.00,312.40
498,2498,14,62.12,869.68,0.08,69.57,800.11
499,2499,15,453.09,6796.35,0.07,475.74,6320.61

In [6]:
columnas_texto = df.select_dtypes(include='object')
columnas_texto

C:\Users\nexts\AppData\Local\Temp\ipykernel_15792\800977465.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columnas_texto = df.select_dtypes(include='object')

,fecha,producto,categoria,region,vendedor,estado
0,2024-01-29,Laptop Dell XPS,Computadoras,Norte,Pedro Sánchez,Completado
1,2024-04-18,Laptop Dell XPS,Computadoras,Centro,Ana García,Pendiente
2,2024-05-19,Disco SSD 1TB,Almacenamiento,Este,Ana García,Pendiente
3,2024-04-18,Auriculares Bluetooth,Audio,Este,Ana García,Completado
4,2024-04-07,Mouse Logitech,Accesorios,Centro,María López,Completado
...,...,...,...,...,...,...
495,2024-03-18,Webcam HD,Accesorios,Norte,Carlos Méndez,Pendiente
496,2024-03-17,Memoria RAM 16GB,Componentes,Oeste,Lucía Rodríguez,Completado
497,2024-02-18,Memoria RAM 16GB,Componentes,Oeste,Pedro Sánchez,En proceso
498,2024-05-12,Auriculares Bluetooth,Audio,Norte,María López,En proceso
499,2024-02-04,Tablet Samsung,Computadoras,Sur,Ana García,Pendiente

### Filtrado de filas por condiciones booleanas

In [8]:
df['total']>1000

0       True
1       True
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499     True
Name: total, Length: 500, dtype: bool

In [9]:
df[df['total']>1000]

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total,region,vendedor,estado
0,2000,2024-01-29,Laptop Dell XPS,Computadoras,12,1173.00,14076.00,0.07,985.32,13090.68,Norte,Pedro Sánchez,Completado
1,2001,2024-04-18,Laptop Dell XPS,Computadoras,1,1151.24,1151.24,0.07,80.59,1070.65,Centro,Ana García,Pendiente
6,2006,2024-05-27,"Monitor LG 27""",Monitores,12,334.93,4019.16,0.12,482.30,3536.86,Este,Ana García,Pendiente
10,2010,2024-01-15,"Monitor LG 27""",Monitores,14,333.62,4670.68,0.08,373.65,4297.03,Este,Ana García,Pendiente
13,2013,2024-05-29,Disco SSD 1TB,Almacenamiento,15,121.00,1815.00,0.09,163.35,1651.65,Sur,Lucía Rodríguez,En proceso
...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,2487,2024-02-02,Laptop Dell XPS,Computadoras,7,1149.40,8045.80,0.12,965.50,7080.30,Sur,Pedro Sánchez,Pendiente
491,2491,2024-01-28,Impresora HP,Impresoras,13,172.82,2246.66,0.08,179.73,2066.93,Centro,María López,En proceso
492,2492,2024-03-08,Disco SSD 1TB,Almacenamiento,11,119.83,1318.13,0.11,144.99,1173.14,Norte,Carlos Méndez,Cancelado
494,2494,2024-03-01,Laptop Dell XPS,Computadoras,12,1197.03,14364.36,0.08,1149.15,13215.21,Este,Ana García,Cancelado
499,2499,2024-02-04,Tablet Samsung,Computadoras,15,453.09,6796.35,0.07,475.74,6320.61,Sur,Ana García,Pendiente

In [11]:
df[df['region']=='Norte']

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total,region,vendedor,estado
0,2000,2024-01-29,Laptop Dell XPS,Computadoras,12,1173.00,14076.00,0.07,985.32,13090.68,Norte,Pedro Sánchez,Completado
27,2027,2024-01-25,Disco SSD 1TB,Almacenamiento,6,119.08,714.48,0.05,35.72,678.76,Norte,Pedro Sánchez,Completado
30,2030,2024-01-20,Memoria RAM 16GB,Componentes,13,77.71,1010.23,0.11,111.13,899.10,Norte,Pedro Sánchez,Completado
39,2039,2024-01-19,Laptop Dell XPS,Computadoras,8,1214.54,9716.32,0.11,1068.80,8647.52,Norte,Ana García,Pendiente
40,2040,2024-05-09,Webcam HD,Accesorios,3,46.95,140.85,0.00,0.00,140.85,Norte,Carlos Méndez,Cancelado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,2489,2024-05-21,Auriculares Bluetooth,Audio,14,63.55,889.70,0.05,44.49,845.21,Norte,Pedro Sánchez,En proceso
492,2492,2024-03-08,Disco SSD 1TB,Almacenamiento,11,119.83,1318.13,0.11,144.99,1173.14,Norte,Carlos Méndez,Cancelado
493,2493,2024-04-13,Teclado Mecánico,Accesorios,10,85.92,859.20,0.07,60.14,799.06,Norte,Juan Pérez,Cancelado
495,2495,2024-03-18,Webcam HD,Accesorios,5,46.54,232.70,0.00,0.00,232.70,Norte,Carlos Méndez,Pendiente
498,2498,2024-05-12,Auriculares Bluetooth,Audio,14,62.12,869.68,0.08,69.57,800.11,Norte,María López,En proceso

In [13]:
df[(df['region']=='Norte') & (df['total']>500)]

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total,region,vendedor,estado
0,2000,2024-01-29,Laptop Dell XPS,Computadoras,12,1173.00,14076.00,0.07,985.32,13090.68,Norte,Pedro Sánchez,Completado
27,2027,2024-01-25,Disco SSD 1TB,Almacenamiento,6,119.08,714.48,0.05,35.72,678.76,Norte,Pedro Sánchez,Completado
30,2030,2024-01-20,Memoria RAM 16GB,Componentes,13,77.71,1010.23,0.11,111.13,899.10,Norte,Pedro Sánchez,Completado
39,2039,2024-01-19,Laptop Dell XPS,Computadoras,8,1214.54,9716.32,0.11,1068.80,8647.52,Norte,Ana García,Pendiente
49,2049,2024-03-01,Teclado Mecánico,Accesorios,13,87.64,1139.32,0.14,159.50,979.82,Norte,Carlos Méndez,Cancelado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,2488,2024-03-07,Auriculares Bluetooth,Audio,15,66.48,997.20,0.08,79.78,917.42,Norte,Juan Pérez,En proceso
489,2489,2024-05-21,Auriculares Bluetooth,Audio,14,63.55,889.70,0.05,44.49,845.21,Norte,Pedro Sánchez,En proceso
492,2492,2024-03-08,Disco SSD 1TB,Almacenamiento,11,119.83,1318.13,0.11,144.99,1173.14,Norte,Carlos Méndez,Cancelado
493,2493,2024-04-13,Teclado Mecánico,Accesorios,10,85.92,859.20,0.07,60.14,799.06,Norte,Juan Pérez,Cancelado
498,2498,2024-05-12,Auriculares Bluetooth,Audio,14,62.12,869.68,0.08,69.57,800.11,Norte,María López,En proceso

In [14]:
df[(df['total']>=500) & (df['total']<=1500)]

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total,region,vendedor,estado
1,2001,2024-04-18,Laptop Dell XPS,Computadoras,1,1151.24,1151.24,0.07,80.59,1070.65,Centro,Ana García,Pendiente
5,2005,2024-04-27,Tablet Samsung,Computadoras,2,471.29,942.58,0.04,37.70,904.88,Centro,María López,Cancelado
7,2007,2024-01-26,Disco SSD 1TB,Almacenamiento,5,119.44,597.20,0.08,47.78,549.42,Sur,María López,Cancelado
8,2008,2024-02-23,Webcam HD,Accesorios,12,46.96,563.52,0.06,33.81,529.71,Centro,Pedro Sánchez,Pendiente
9,2009,2024-05-16,"Monitor LG 27""",Monitores,3,348.68,1046.04,0.08,83.68,962.36,Centro,Carlos Méndez,Cancelado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,2489,2024-05-21,Auriculares Bluetooth,Audio,14,63.55,889.70,0.05,44.49,845.21,Norte,Pedro Sánchez,En proceso
492,2492,2024-03-08,Disco SSD 1TB,Almacenamiento,11,119.83,1318.13,0.11,144.99,1173.14,Norte,Carlos Méndez,Cancelado
493,2493,2024-04-13,Teclado Mecánico,Accesorios,10,85.92,859.20,0.07,60.14,799.06,Norte,Juan Pérez,Cancelado
496,2496,2024-03-17,Memoria RAM 16GB,Componentes,13,77.44,1006.72,0.08,80.54,926.18,Oeste,Lucía Rodríguez,Completado
498,2498,2024-05-12,Auriculares Bluetooth,Audio,14,62.12,869.68,0.08,69.57,800.11,Norte,María López,En proceso

In [15]:
df[(df['region']=='Norte') | (df['region']=='Sur')]

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total,region,vendedor,estado
0,2000,2024-01-29,Laptop Dell XPS,Computadoras,12,1173.00,14076.00,0.07,985.32,13090.68,Norte,Pedro Sánchez,Completado
7,2007,2024-01-26,Disco SSD 1TB,Almacenamiento,5,119.44,597.20,0.08,47.78,549.42,Sur,María López,Cancelado
13,2013,2024-05-29,Disco SSD 1TB,Almacenamiento,15,121.00,1815.00,0.09,163.35,1651.65,Sur,Lucía Rodríguez,En proceso
24,2024,2024-01-02,Mouse Logitech,Accesorios,12,25.33,303.96,0.00,0.00,303.96,Sur,Ana García,Completado
27,2027,2024-01-25,Disco SSD 1TB,Almacenamiento,6,119.08,714.48,0.05,35.72,678.76,Norte,Pedro Sánchez,Completado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,2492,2024-03-08,Disco SSD 1TB,Almacenamiento,11,119.83,1318.13,0.11,144.99,1173.14,Norte,Carlos Méndez,Cancelado
493,2493,2024-04-13,Teclado Mecánico,Accesorios,10,85.92,859.20,0.07,60.14,799.06,Norte,Juan Pérez,Cancelado
495,2495,2024-03-18,Webcam HD,Accesorios,5,46.54,232.70,0.00,0.00,232.70,Norte,Carlos Méndez,Pendiente
498,2498,2024-05-12,Auriculares Bluetooth,Audio,14,62.12,869.68,0.08,69.57,800.11,Norte,María López,En proceso
499,2499,2024-02-04,Tablet Samsung,Computadoras,15,453.09,6796.35,0.07,475.74,6320.61,Sur,Ana García,Pendiente

In [18]:
df[df['region'].isin(['Norte', 'Sur'])]

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total,region,vendedor,estado
0,2000,2024-01-29,Laptop Dell XPS,Computadoras,12,1173.00,14076.00,0.07,985.32,13090.68,Norte,Pedro Sánchez,Completado
7,2007,2024-01-26,Disco SSD 1TB,Almacenamiento,5,119.44,597.20,0.08,47.78,549.42,Sur,María López,Cancelado
13,2013,2024-05-29,Disco SSD 1TB,Almacenamiento,15,121.00,1815.00,0.09,163.35,1651.65,Sur,Lucía Rodríguez,En proceso
24,2024,2024-01-02,Mouse Logitech,Accesorios,12,25.33,303.96,0.00,0.00,303.96,Sur,Ana García,Completado
27,2027,2024-01-25,Disco SSD 1TB,Almacenamiento,6,119.08,714.48,0.05,35.72,678.76,Norte,Pedro Sánchez,Completado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,2492,2024-03-08,Disco SSD 1TB,Almacenamiento,11,119.83,1318.13,0.11,144.99,1173.14,Norte,Carlos Méndez,Cancelado
493,2493,2024-04-13,Teclado Mecánico,Accesorios,10,85.92,859.20,0.07,60.14,799.06,Norte,Juan Pérez,Cancelado
495,2495,2024-03-18,Webcam HD,Accesorios,5,46.54,232.70,0.00,0.00,232.70,Norte,Carlos Méndez,Pendiente
498,2498,2024-05-12,Auriculares Bluetooth,Audio,14,62.12,869.68,0.08,69.57,800.11,Norte,María López,En proceso
499,2499,2024-02-04,Tablet Samsung,Computadoras,15,453.09,6796.35,0.07,475.74,6320.61,Sur,Ana García,Pendiente

In [22]:
df[~(df['estado'] == 'Completado')]

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total,region,vendedor,estado
1,2001,2024-04-18,Laptop Dell XPS,Computadoras,1,1151.24,1151.24,0.07,80.59,1070.65,Centro,Ana García,Pendiente
2,2002,2024-05-19,Disco SSD 1TB,Almacenamiento,4,119.39,477.56,0.00,0.00,477.56,Este,Ana García,Pendiente
5,2005,2024-04-27,Tablet Samsung,Computadoras,2,471.29,942.58,0.04,37.70,904.88,Centro,María López,Cancelado
6,2006,2024-05-27,"Monitor LG 27""",Monitores,12,334.93,4019.16,0.12,482.30,3536.86,Este,Ana García,Pendiente
7,2007,2024-01-26,Disco SSD 1TB,Almacenamiento,5,119.44,597.20,0.08,47.78,549.42,Sur,María López,Cancelado
...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,2494,2024-03-01,Laptop Dell XPS,Computadoras,12,1197.03,14364.36,0.08,1149.15,13215.21,Este,Ana García,Cancelado
495,2495,2024-03-18,Webcam HD,Accesorios,5,46.54,232.70,0.00,0.00,232.70,Norte,Carlos Méndez,Pendiente
497,2497,2024-02-18,Memoria RAM 16GB,Componentes,4,78.10,312.40,0.00,0.00,312.40,Oeste,Pedro Sánchez,En proceso
498,2498,2024-05-12,Auriculares Bluetooth,Audio,14,62.12,869.68,0.08,69.57,800.11,Norte,María López,En proceso
499,2499,2024-02-04,Tablet Samsung,Computadoras,15,453.09,6796.35,0.07,475.74,6320.61,Sur,Ana García,Pendiente

In [27]:
df[ df['producto'].str.contains('lAptop', case=False) ]

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,monto_descuento,total,region,vendedor,estado
0,2000,2024-01-29,Laptop Dell XPS,Computadoras,12,1173.00,14076.00,0.07,985.32,13090.68,Norte,Pedro Sánchez,Completado
1,2001,2024-04-18,Laptop Dell XPS,Computadoras,1,1151.24,1151.24,0.07,80.59,1070.65,Centro,Ana García,Pendiente
14,2014,2024-01-24,Laptop Dell XPS,Computadoras,14,1153.16,16144.24,0.11,1775.87,14368.37,Oeste,Lucía Rodríguez,Completado
32,2032,2024-04-07,Laptop Dell XPS,Computadoras,7,1171.82,8202.74,0.13,1066.36,7136.38,Oeste,María López,En proceso
34,2034,2024-03-21,Laptop Dell XPS,Computadoras,1,1210.10,1210.10,0.10,121.01,1089.09,Centro,Carlos Méndez,Completado
39,2039,2024-01-19,Laptop Dell XPS,Computadoras,8,1214.54,9716.32,0.11,1068.80,8647.52,Norte,Ana García,Pendiente
45,2045,2024-03-11,Laptop Dell XPS,Computadoras,1,1180.03,1180.03,0.06,70.80,1109.23,Este,Carlos Méndez,En proceso
80,2080,2024-02-21,Laptop Dell XPS,Computadoras,10,1158.29,11582.90,0.06,694.97,10887.93,Norte,Lucía Rodríguez,Pendiente
92,2092,2024-04-24,Laptop Dell XPS,Computadoras,2,1175.31,2350.62,0.09,211.56,2139.06,Sur,María López,Cancelado
98,2098,2024-03-11,Laptop Dell XPS,Computadoras,1,1206.40,1206.40,0.12,144.77,1061.63,Sur,Pedro Sánchez,En proceso
99,2099,2024-01-27,Laptop Dell XPS,Computadoras,10,1174.12,11741.20,0.10,1174.12,10567.08,Este,Carlos Méndez,Completado
101,2101,2024-05-27,Laptop Dell XPS,Computadoras,3,1157.90,3473.70,0.11,382.11,3091.59,Este,Ana García,Pendiente
106,2106,2024-03-15,Laptop Dell XPS,Computadoras,4,1174.57,4698.28,0.08,375.86,4322.42,Oeste,Ana García,Pendiente
111,2111,2024-03-05,Laptop Dell XPS,Computadoras,2,1167.47,2334.94,0.12,280.19,2054.75,Centro,Lucía Rodríguez,Completado
119,2119,2024-02-01,Laptop Dell XPS,Computadoras,11,1213.06,13343.66,0.07,934.06,12409.60,Sur,María López,Completado
133,2133,2024-03-17,Laptop Dell XPS,Computadoras,1,1178.92,1178.92,0.06,70.74,1108.18,Este,María López,En proceso
140,2140,2024-03-11,Laptop Dell XPS,Computadoras,10,1243.81,12438.10,0.13,1616.95,10821.15,Norte,Lucía Rodríguez,En proceso
163,2163,2024-01-08,Laptop Dell XPS,Computadoras,8,1241.68,9933.44,0.09,894.01,9039.43,Norte,Juan Pérez,En proceso
175,2175,2024-03-09,Laptop Dell XPS,Computadoras,3,1172.79,3518.37,0.13,457.39,3060.98,Este,María López,Completado
183,2183,2024-01-31,Laptop Dell XPS,Computadoras,8,1229.64,9837.12,0.07,688.60,9148.52,Oeste,Lucía Rodríguez,Pendiente
185,2185,2024-04-21,Laptop Dell XPS,Computadoras,8,1250.54,10004.32,0.14,1400.60,8603.72,Centro,Juan Pérez,En proceso
207,2207,2024-04-22,Laptop Dell XPS,Computadoras,7,1183.72,8286.04,0.12,994.32,7291.72,Oeste,Lucía Rodríguez,Cancelado
219,2219,2024-05-17,Laptop Dell XPS,Computadoras,11,1201.85,13220.35,0.07,925.42,12294.93,Sur,María López,En proceso
222,2222,2024-04-30,Laptop Dell XPS,Computadoras,11,1186.43,13050.73,0.09,1174.57,11876.16,Norte,María López,Completado
224,2224,2024-02-04,Laptop Dell XPS,Computadoras,6,1205.52,7233.12,0.13,940.31,6292.81,Sur,Pedro Sánchez,En proceso
226,2226,2024-02-21,Laptop Dell XPS,Computadoras,13,1163.94,15131.22,0.05,756.56,14374.66,Este,Lucía Rodríguez,En proceso
233,2233,2024-03-11,Laptop Dell XPS,Computadoras,2,1220.54,2441.08,0.09,219.70,2221.38,Centro,Pedro Sánchez,Pendiente
252,2252,2024-01-21,Laptop Dell XPS,Computadoras,11,1232.52,13557.72,0.08,1084.62,12473.10,Sur,Lucía Rodríguez,En proceso
285,2285,2024-05-16,Laptop Dell XPS,Computadoras,15,1250.58,18758.70,0.09,1688.28,17070.42,Sur,Ana García,En proceso
310,2310,2024-03-03,Laptop Dell XPS,Computadoras,7,1192.68,8348.76,0.10,834.88,7513.88,Norte,Carlos Méndez,Cancelado
328,2328,2024-05-18,Laptop Dell XPS,Computadoras,9,1144.06,10296.54,0.13,1338.55,8957.99,Norte,Ana García,En proceso
331,2331,2024-01-05,Laptop Dell XPS,Computadoras,9,1206.20,10855.80,0.05,542.79,10313.01,Centro,Pedro Sánchez,Cancelado
343,2343,2024-03-24,Laptop Dell XPS,Computadoras,11,1172.80,12900.80,0.15,1935.12,10965.68,Oeste,Carlos Méndez,Cancelado
364,2364,2024-01-28,Laptop Dell XPS,Computadoras,2,1171.05,2342.10,0.10,234.21,2107.89,Centro,Lucía Rodríguez,Pendiente
366,2366,2024-03-29,Laptop Dell XPS,Computadoras,8,1152.55,9220.40,0.09,829.84,8390.56,Norte,Ana García,Pendiente
369,2369,2024-03-17,Laptop Dell XPS,Computadoras,13,1225.29,15928.77,0.05,796.44,15132.33,Este,Pedro Sánchez,Completado
380,2380,2024-04-01,Laptop Dell XPS,Computadoras,8,1156.38,9251.04,0.13,1202.64,8048.40,Centro,Lucía Rodríguez,En proceso
398,2398,2024-04-27,Laptop Dell XPS,Computadoras,2,1251.53,2503.06,0.07,175.21,2327.85,Oeste,Ana García,En proceso
410,2410,2024-03-16,Laptop Dell XPS,Computadoras,13,1247.75,16220.75,0.15,2433.11,13787.64,Oeste,Juan Pérez,Completado
414,2414,2024-01-11,Laptop Dell XPS,Computadoras,13,1187.76,15440.88,0.08,1235.27,14205.61,Centro,Juan Pérez,En proceso
418,2418,2024-03-02,Laptop Dell XPS,Computadoras,4,1150.35,4601.40,0.09,414.13,4187.27,Oeste,Lucía Rodríguez,Completado
425,2425,2024-01-12,Laptop Dell XPS,Computadoras,4,1145.52,4582.08,0.09,412.39,4169.69,Sur,Carlos Méndez,Completado
433,2433,2024-03-26,Laptop Dell XPS,Computadoras,13,1218.88,15845.44,0.13,2059.91,13785.53,Este,Ana García,Pendiente
435,2435,2024-01-24,Laptop Dell XPS,Computadoras,15,1167.78,17516.70,0.13,2277.17,15239.53,Oeste,Pedro Sánchez,Cancelado
447,2447,2024-01-20,Laptop Dell XPS,Computadoras,2,1163.73,2327.46,0.11,256.02,2071.44,Sur,Ana García,Cancelado
448,2448,2024-02-01,Laptop Dell XPS,Computadoras,8,1146.08,9168.64,0.14,1283.61,7885.03,Oeste,Pedro Sánchez,En proceso
449,2449,2024-05-07,Laptop Dell XPS,Computadoras,7,1221.99,8553.93,0.07,598.78,7955.15,Sur,Carlos Méndez,Cancelado
455,2455,2024-03-12,Laptop Dell XPS,Computadoras,13,1258.98,16366.74,0.10,1636.67,14730.07,Centro,Carlos Méndez,Pendiente
469,2469,2024-04-24,Laptop Dell XPS,Computadoras,5,1165.16,5825.80,0.12,699.10,5126.70,Este,María López,Completado
470,2470,2024-01-01,Laptop Dell XPS,Computadoras,7,1192.59,8348.13,0.09,751.33,7596.80,Sur,Juan Pérez,En proceso
478,2478,2024-04-02,Laptop Dell XPS,Computadoras,7,1150.52,8053.64,0.13,1046.97,7006.67,Centro,Juan Pérez,Pendiente
479,2479,2024-01-25,Laptop Dell XPS,Computadoras,4,1160.50,4642.00,0.08,371.36,4270.64,Norte,Juan Pérez,Completado
484,2484,2024-05-21,Laptop Dell XPS,Computadoras,14,1186.45,16610.30,0.10,1661.03,14949.27,Centro,Pedro Sánchez,En proceso
487,2487,2024-02-02,Laptop Dell XPS,Computadoras,7,1149.40,8045.80,0.12,965.50,7080.30,Sur,Pedro Sánchez,Pendiente
494,2494,2024-03-01,Laptop Dell XPS,Computadoras,12,1197.03,14364.36,0.08,1149.15,13215.21,Este,Ana García,Cancelado

### Indexación con .loc e .iloc

Diferencia clave:

    .iloc[fila, columna]: usa posiciones numéricas (0, 1, 2...)

    .loc[fila, columna]: usa etiquetas/nombres y condiciones booleanas

In [31]:
df.iloc[0:5, 0:3]

   id_venta       fecha               producto
0      2000  2024-01-29        Laptop Dell XPS
1      2001  2024-04-18        Laptop Dell XPS
2      2002  2024-05-19          Disco SSD 1TB
3      2003  2024-04-18  Auriculares Bluetooth
4      2004  2024-04-07         Mouse Logitech

In [34]:
df.iloc[:,-4:-1]

        total  region         vendedor
0    13090.68   Norte    Pedro Sánchez
1     1070.65  Centro       Ana García
2      477.56    Este       Ana García
3      313.80    Este       Ana García
4      155.22  Centro      María López
..        ...     ...              ...
495    232.70   Norte    Carlos Méndez
496    926.18   Oeste  Lucía Rodríguez
497    312.40   Oeste    Pedro Sánchez
498    800.11   Norte      María López
499   6320.61     Sur       Ana García

[500 rows x 3 columns]

In [36]:
df.columns

Index(['id_venta', 'fecha', 'producto', 'categoria', 'cantidad',
       'precio_unitario', 'subtotal', 'descuento_porcentaje',
       'monto_descuento', 'total', 'region', 'vendedor', 'estado'],
      dtype='str')

In [37]:
df.loc[df['total']>2000, ['producto', 'total']]

            producto     total
0    Laptop Dell XPS  13090.68
6     Monitor LG 27"   3536.86
10    Monitor LG 27"   4297.03
14   Laptop Dell XPS  14368.37
20    Monitor LG 27"   4968.28
..               ...       ...
485   Monitor LG 27"   2496.75
487  Laptop Dell XPS   7080.30
491     Impresora HP   2066.93
494  Laptop Dell XPS  13215.21
499   Tablet Samsung   6320.61

[130 rows x 2 columns]

In [38]:
df.loc[df['total']>2000, 'id_venta': 'descuento_porcentaje']

,id_venta,fecha,producto,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje
0,2000,2024-01-29,Laptop Dell XPS,Computadoras,12,1173.00,14076.00,0.07
6,2006,2024-05-27,"Monitor LG 27""",Monitores,12,334.93,4019.16,0.12
10,2010,2024-01-15,"Monitor LG 27""",Monitores,14,333.62,4670.68,0.08
14,2014,2024-01-24,Laptop Dell XPS,Computadoras,14,1153.16,16144.24,0.11
20,2020,2024-01-15,"Monitor LG 27""",Monitores,15,352.36,5285.40,0.06
...,...,...,...,...,...,...,...,...
485,2485,2024-05-26,"Monitor LG 27""",Monitores,8,342.96,2743.68,0.09
487,2487,2024-02-02,Laptop Dell XPS,Computadoras,7,1149.40,8045.80,0.12
491,2491,2024-01-28,Impresora HP,Impresoras,13,172.82,2246.66,0.08
494,2494,2024-03-01,Laptop Dell XPS,Computadoras,12,1197.03,14364.36,0.08
499,2499,2024-02-04,Tablet Samsung,Computadoras,15,453.09,6796.35,0.07

In [41]:
df.loc[
    (df['region']=='Norte') & 
    (df['estado']=='Completado') &
    (df['total']>500), 
    ['region', 'estado', 'total']
]

    region      estado     total
0    Norte  Completado  13090.68
27   Norte  Completado    678.76
30   Norte  Completado    899.10
75   Norte  Completado    964.00
150  Norte  Completado   1021.41
159  Norte  Completado   2178.12
211  Norte  Completado   5639.17
222  Norte  Completado  11876.16
234  Norte  Completado   1046.38
303  Norte  Completado    671.33
397  Norte  Completado    892.60
424  Norte  Completado    528.03
479  Norte  Completado   4270.64

## U2.03  - Transformaciones de columnas

###	Columnas calculadas con operaciones númericas

In [43]:
import numpy as np #librería para operaciones numéricas

df =pd.read_csv('ventas_completas.csv')
print(list(df.columns))

['id_venta', 'fecha', 'producto', 'categoria', 'cantidad', 'precio_unitario', 'subtotal', 'descuento_porcentaje', 'monto_descuento', 'total', 'region', 'vendedor', 'estado']

In [51]:
df['precio_original'] = df['total'] / df['cantidad']
df['total_con_iva'] = df['total'] * 1.19
df['log_total'] = np.log(df['total'])
df['sqrt_total'] = np.sqrt(df['total'])
df[['total', 'cantidad', 'precio_original','total_con_iva','log_total','sqrt_total']].round(2)

        total  cantidad  precio_original  total_con_iva  log_total  sqrt_total
0    13090.68        12          1090.89       15577.91       9.48      114.41
1     1070.65         1          1070.65        1274.07       6.98       32.72
2      477.56         4           119.39         568.30       6.17       21.85
3      313.80         5            62.76         373.42       5.75       17.71
4      155.22         6            25.87         184.71       5.04       12.46
..        ...       ...              ...            ...        ...         ...
495    232.70         5            46.54         276.91       5.45       15.25
496    926.18        13            71.24        1102.15       6.83       30.43
497    312.40         4            78.10         371.76       5.74       17.67
498    800.11        14            57.15         952.13       6.68       28.29
499   6320.61        15           421.37        7521.53       8.75       79.50

[500 rows x 6 columns]

### Columnas Calculadas con operaciones de texto.

Operaciones con Columnas de Texto

In [58]:
df['marca']= df['producto'].str.split(' ').str[1]
df['es_laptop'] = df['producto'].str.contains('laptop', case=False)
df['largo_nombre'] = df['producto'].str.len()
df['producto_largo'] = df['producto'] + '(' + df['largo_nombre'].astype(str) + ' caracteres)'
df[['producto', 'marca', 'es_laptop', 'largo_nombre', 'producto_largo']]

,producto,marca,es_laptop,largo_nombre,producto_largo
0,Laptop Dell XPS,Dell,True,15,Laptop Dell XPS(15 caracteres)
1,Laptop Dell XPS,Dell,True,15,Laptop Dell XPS(15 caracteres)
2,Disco SSD 1TB,SSD,False,13,Disco SSD 1TB(13 caracteres)
3,Auriculares Bluetooth,Bluetooth,False,21,Auriculares Bluetooth(21 caracteres)
4,Mouse Logitech,Logitech,False,14,Mouse Logitech(14 caracteres)
...,...,...,...,...,...
495,Webcam HD,HD,False,9,Webcam HD(9 caracteres)
496,Memoria RAM 16GB,RAM,False,16,Memoria RAM 16GB(16 caracteres)
497,Memoria RAM 16GB,RAM,False,16,Memoria RAM 16GB(16 caracteres)
498,Auriculares Bluetooth,Bluetooth,False,21,Auriculares Bluetooth(21 caracteres)
499,Tablet Samsung,Samsung,False,14,Tablet Samsung(14 caracteres)

### Columnas calculada con condicionales lógicas

In [64]:
df['tipo_venta'] = np.where(df['total']>1000, 'Alta', 'Baja')

condiciones = [
    (df['total']>=2000),
    (df['total']>=1000),
    (df['total']>=500)
]
valores = ['Premium', 'Alta', 'Media']

df['categoria_venta'] = np.select(condiciones, valores, default='Baja')
df[['total', 'tipo_venta', 'categoria_venta']]

        total tipo_venta categoria_venta
0    13090.68       Alta         Premium
1     1070.65       Alta            Alta
2      477.56       Baja            Baja
3      313.80       Baja            Baja
4      155.22       Baja            Baja
..        ...        ...             ...
495    232.70       Baja            Baja
496    926.18       Baja           Media
497    312.40       Baja            Baja
498    800.11       Baja           Media
499   6320.61       Alta         Premium

[500 rows x 3 columns]

## U2.04  - Agrupaciones y agregaciones

###  Agrupar datos con .groupby()

In [4]:
import pandas as pd
import numpy as np #librería para operaciones numéricas
df =pd.read_csv('ventas_completas.csv')
print(list(df.columns))

['id_venta', 'fecha', 'producto', 'categoria', 'cantidad', 'precio_unitario', 'subtotal', 'descuento_porcentaje', 'monto_descuento', 'total', 'region', 'vendedor', 'estado']

In [13]:
df.groupby(['region', 'estado'])['total'].sum().sort_values(ascending=False).reset_index()
#df.groupby(['region', 'estado'])['total'].sum().reset_index().sort_values(by='total', ascending=False)

    region      estado     total
0   Centro  En proceso  80009.10
1      Sur  En proceso  66471.08
2    Oeste  Completado  66210.33
3    Norte  En proceso  63782.13
4    Oeste   Cancelado  62079.57
5   Centro   Pendiente  56338.93
6    Norte   Pendiente  53788.67
7    Oeste  En proceso  53210.39
8     Este  Completado  51308.89
9    Norte  Completado  45627.02
10   Oeste   Pendiente  43759.08
11     Sur   Cancelado  41462.73
12     Sur  Completado  39615.07
13  Centro   Cancelado  38284.70
14    Este  En proceso  38026.61
15    Este   Cancelado  37363.74
16    Este   Pendiente  34288.26
17  Centro  Completado  30373.60
18   Norte   Cancelado  28860.27
19     Sur   Pendiente  27678.04

In [38]:
df.groupby('region')['total'].sum()

region
Centro    205006.33
Este      160987.50
Norte     192058.09
Oeste     225259.37
Sur       175226.92
Name: total, dtype: float64

### Funciones de agregación: .sum(), .mean(), .count() y agg()

In [39]:
df.groupby(['region', 'estado'])['total'].agg(['sum', 'mean', 'max', 'min']).sort_values(by='sum', ascending=False).reset_index().round(2)

    region      estado       sum     mean       max     min
0   Centro  En proceso  80009.10  3636.78  14949.27   68.00
1      Sur  En proceso  66471.08  2461.89  17070.42   64.34
2    Oeste  Completado  66210.33  2546.55  14368.37   45.01
3    Norte  En proceso  63782.13  2199.38  10821.15  170.31
4    Oeste   Cancelado  62079.57  2699.11  15239.53  143.94
5   Centro   Pendiente  56338.93  1482.60  14730.07   43.99
6    Norte   Pendiente  53788.67  2338.64  10887.93   25.22
7    Oeste  En proceso  53210.39  1716.46   7885.03   71.28
8     Este  Completado  51308.89  2443.28  15132.33  116.80
9    Norte  Completado  45627.02  2073.96  13090.68   51.66
10   Oeste   Pendiente  43759.08  1750.36   9148.52   48.84
11     Sur   Cancelado  41462.73  1658.51   7955.15   90.10
12     Sur  Completado  39615.07  2085.00  12409.60  161.72
13  Centro   Cancelado  38284.70  1531.39  10313.01   65.00
14    Este  En proceso  38026.61  1810.79  14374.66   49.14
15    Este   Cancelado  37363.74  1098.93  13215.21   62.50
16    Este   Pendiente  34288.26  1804.65  13785.53   72.09
17  Centro  Completado  30373.60  1214.94   6506.84   43.74
18   Norte   Cancelado  28860.27  1154.41   7513.88  140.85
19     Sur   Pendiente  27678.04  1383.90   7080.30   71.93

In [40]:
df.groupby(['region', 'estado']).agg({
    'total':['sum', 'mean', 'max', 'min'], 
    'cantidad':['sum','mean']
    }).reset_index().round(2).sort_values(by=('total','sum'), ascending=False)

    region      estado     total                            cantidad
                             sum     mean       max     min      sum  mean
2   Centro  En proceso  80009.10  3636.78  14949.27   68.00      194  8.82
18     Sur  En proceso  66471.08  2461.89  17070.42   64.34      184  6.81
13   Oeste  Completado  66210.33  2546.55  14368.37   45.01      218  8.38
10   Norte  En proceso  63782.13  2199.38  10821.15  170.31      277  9.55
12   Oeste   Cancelado  62079.57  2699.11  15239.53  143.94      203  8.83
3   Centro   Pendiente  56338.93  1482.60  14730.07   43.99      280  7.37
11   Norte   Pendiente  53788.67  2338.64  10887.93   25.22      195  8.48
14   Oeste  En proceso  53210.39  1716.46   7885.03   71.28      257  8.29
5     Este  Completado  51308.89  2443.28  15132.33  116.80      172  8.19
9    Norte  Completado  45627.02  2073.96  13090.68   51.66      170  7.73
15   Oeste   Pendiente  43759.08  1750.36   9148.52   48.84      186  7.44
16     Sur   Cancelado  41462.73  1658.51   7955.15   90.10      170  6.80
17     Sur  Completado  39615.07  2085.00  12409.60  161.72      158  8.32
0   Centro   Cancelado  38284.70  1531.39  10313.01   65.00      206  8.24
6     Este  En proceso  38026.61  1810.79  14374.66   49.14      167  7.95
4     Este   Cancelado  37363.74  1098.93  13215.21   62.50      225  6.62
7     Este   Pendiente  34288.26  1804.65  13785.53   72.09      143  7.53
1   Centro  Completado  30373.60  1214.94   6506.84   43.74      207  8.28
8    Norte   Cancelado  28860.27  1154.41   7513.88  140.85      207  8.28
19     Sur   Pendiente  27678.04  1383.90   7080.30   71.93      155  7.75

### Análisis por categorías y segmentos

In [41]:
pd.crosstab(
    df['region'],
    df['estado'],
    values=df['total'],
    aggfunc='sum'
).round(2)

estado  Cancelado  Completado  En proceso  Pendiente
region
Centro   38284.70    30373.60    80009.10   56338.93
Este     37363.74    51308.89    38026.61   34288.26
Norte    28860.27    45627.02    63782.13   53788.67
Oeste    62079.57    66210.33    53210.39   43759.08
Sur      41462.73    39615.07    66471.08   27678.04

In [42]:
df.pivot_table(
    values='total',
    index=['region', 'estado'],
    columns='categoria',
    aggfunc='sum',
    fill_value=0
).reset_index().round(2)

categoria,region,estado,Accesorios,Almacenamiento,Audio,Componentes,Computadoras,Impresoras,Monitores
0,Centro,Cancelado,3441.74,1969.36,1415.46,2270.97,20796.35,2703.92,5686.90
1,Centro,Completado,3342.83,4393.22,559.77,0.00,9650.68,8406.29,4020.81
2,Centro,En proceso,1541.40,0.00,68.00,1485.85,60710.78,2254.65,13948.42
3,Centro,Pendiente,3898.60,1580.65,2045.04,2801.92,28778.34,6855.64,10378.74
4,Este,Cancelado,6071.78,1822.45,1301.44,998.33,20695.07,2956.22,3518.45
5,Este,Completado,3012.93,1023.73,2142.10,0.00,37699.19,3200.69,4230.25
6,Este,En proceso,1680.92,2592.70,1196.67,1034.37,19652.94,4518.22,7350.79
7,Este,Pendiente,769.36,2178.16,902.09,2049.20,16877.12,2418.89,9093.44
8,Norte,Cancelado,5651.68,2745.00,850.98,2768.76,11706.62,3090.04,2047.19
9,Norte,Completado,2333.85,1149.16,805.11,3931.59,37054.77,0.00,352.54
10,Norte,En proceso,2453.40,891.83,4072.18,979.80,35557.69,2702.26,17124.97
11,Norte,Pendiente,3939.04,1056.91,1459.45,0.00,31123.42,2550.55,13659.30
12,Oeste,Cancelado,1967.82,1952.61,710.84,566.06,43207.91,4975.59,8698.74
13,Oeste,Completado,1428.20,2441.56,319.25,1618.60,47334.38,3337.17,9731.17
14,Oeste,En proceso,3092.37,4395.20,968.57,2363.00,29739.60,3618.65,9033.00
15,Oeste,Pendiente,2085.70,2070.12,0.00,2513.41,27824.52,3360.91,5904.42
16,Sur,Cancelado,340.57,4443.45,876.39,2040.66,19721.58,3453.00,10587.08
17,Sur,Completado,2387.95,1776.00,766.81,732.63,23357.84,1398.59,9195.25
18,Sur,En proceso,2406.60,4434.71,900.11,144.62,58400.30,184.74,0.00
19,Sur,Pendiente,1816.28,1983.27,839.23,1282.52,13400.91,1168.16,7187.67

## U2.05 - Uniones y combinaciones 

Diferencias clave entre merge y concat:

- **merge():** Une DataFrames por columnas comunes

- **concat():** Apila DataFrames vertical u horizontalmente

### Combinaciones de tablas con Merge.

Resumen de tipos de join:

| Tipo  | Descripción                                  | Cuándo usar                            |
| ----- | -------------------------------------------- | -------------------------------------- |
| inner | Solo registros que coinciden en ambas tablas | Necesitas datos completos              |
| left  | Todos los registros de la tabla izquierda    | Base principal + información adicional |
| right | Todos los registros de la tabla derecha      | Menos común, similar a left invertido  |
| outer | Todos los registros de ambas tablas          | Análisis completo, detectar faltantes  |

Tipos de Join

In [6]:
import pandas as pd
#Crear datasets de ejemplo
productos_ejemplo = pd.DataFrame(
    {
    'id_producto': [1, 2, 3, 4],
    'productos  ': ['Laptop', 'Tablet', 'Smartphone', 'Monitor'],
    'monto_unit': [100, 200, 150, 300]
    }
)

ventas_ejemplo = pd.DataFrame(
    {
    'id_venta': [1, 2, 3, 4, 5, 6],
    'cliente': ['Ana', 'Ana', 'María', 'Juan', 'José', 'Miguel'],
    'id_producto': [1, 2, 5, 6, 1, 1],
    'cantidad ': [2, 1, 3, 2, 1, 1]
    }
)

pd.merge(
ventas_ejemplo, 
productos_ejemplo, 
how='inner',
on='id_producto'
)

   id_venta cliente  id_producto  cantidad  productos    monto_unit
0         1     Ana            1          2      Laptop         100
1         2     Ana            2          1      Tablet         200
2         5    José            1          1      Laptop         100
3         6  Miguel            1          1      Laptop         100

In [9]:
import pandas as pd
#Crear datasets de ejemplo
productos_ejemplo = pd.DataFrame(
    {
    'id_producto2': [1, 2, 3, 4],
    'productos  ': ['Laptop', 'Tablet', 'Smartphone', 'Monitor'],
    'monto_unit': [100, 200, 150, 300]
    }
)

ventas_ejemplo = pd.DataFrame(
    {
    'id_venta': [1, 2, 3, 4, 5, 6],
    'cliente': ['Ana', 'Ana', 'María', 'Juan', 'José', 'Miguel'],
    'id_producto': [1, 2, 5, 6, 1, 1],
    'cantidad ': [2, 1, 3, 2, 1, 1]
    }
)

pd.merge(
ventas_ejemplo, 
productos_ejemplo, 
how='left',
left_on='id_producto',
right_on='id_producto2'
)

,id_venta,cliente,id_producto,cantidad,id_producto2,productos,monto_unit
0,1,Ana,1,2,1.0,Laptop,100.0
1,2,Ana,2,1,2.0,Tablet,200.0
2,3,María,5,3,NaN,NaN,NaN
3,4,Juan,6,2,NaN,NaN,NaN
4,5,José,1,1,1.0,Laptop,100.0
5,6,Miguel,1,1,1.0,Laptop,100.0

In [10]:
import pandas as pd
#Crear datasets de ejemplo
productos_ejemplo = pd.DataFrame(
    {
    'id_producto2': [1, 2, 3, 4],
    'productos  ': ['Laptop', 'Tablet', 'Smartphone', 'Monitor'],
    'monto_unit': [100, 200, 150, 300]
    }
)

ventas_ejemplo = pd.DataFrame(
    {
    'id_venta': [1, 2, 3, 4, 5, 6],
    'cliente': ['Ana', 'Ana', 'María', 'Juan', 'José', 'Miguel'],
    'id_producto': [1, 2, 5, 6, 1, 1],
    'cantidad ': [2, 1, 3, 2, 1, 1]
    }
)

pd.merge(
ventas_ejemplo, 
productos_ejemplo, 
how='inner',
left_on='id_producto',
right_on='id_producto2'
)

,id_venta,cliente,id_producto,cantidad,id_producto2,productos,monto_unit
0,1,Ana,1,2,1,Laptop,100
1,2,Ana,2,1,2,Tablet,200
2,5,José,1,1,1,Laptop,100
3,6,Miguel,1,1,1,Laptop,100

In [1]:
import pandas as pd
#Crear datasets de ejemplo
productos_ejemplo = pd.DataFrame(
    {
    'id_producto2': [1, 2, 3, 4],
    'productos  ': ['Laptop', 'Tablet', 'Smartphone', 'Monitor'],
    'monto_unit': [100, 200, 150, 300]
    }
)

ventas_ejemplo = pd.DataFrame(
    {
    'id_venta': [1, 2, 3, 4, 5, 6],
    'cliente': ['Ana', 'Ana', 'María', 'Juan', 'José', 'Miguel'],
    'id_producto': [1, 2, 5, 6, 1, 1],
    'cantidad ': [2, 1, 3, 2, 1, 1]
    }
)

pd.merge(
ventas_ejemplo, 
productos_ejemplo, 
how='right',
left_on='id_producto',
right_on='id_producto2'
)

,id_venta,cliente,id_producto,cantidad,id_producto2,productos,monto_unit
0,1.0,Ana,1.0,2.0,1,Laptop,100
1,5.0,José,1.0,1.0,1,Laptop,100
2,6.0,Miguel,1.0,1.0,1,Laptop,100
3,2.0,Ana,2.0,1.0,2,Tablet,200
4,NaN,NaN,NaN,NaN,3,Smartphone,150
5,NaN,NaN,NaN,NaN,4,Monitor,300

In [2]:
import pandas as pd
#Crear datasets de ejemplo
productos_ejemplo = pd.DataFrame(
    {
    'id_producto2': [1, 2, 3, 4],
    'productos  ': ['Laptop', 'Tablet', 'Smartphone', 'Monitor'],
    'monto_unit': [100, 200, 150, 300]
    }
)

ventas_ejemplo = pd.DataFrame(
    {
    'id_venta': [1, 2, 3, 4, 5, 6],
    'cliente': ['Ana', 'Ana', 'María', 'Juan', 'José', 'Miguel'],
    'id_producto': [1, 2, 5, 6, 1, 1],
    'cantidad ': [2, 1, 3, 2, 1, 1]
    }
)

pd.merge(
ventas_ejemplo, 
productos_ejemplo, 
how='outer',
left_on='id_producto',
right_on='id_producto2'
)

,id_venta,cliente,id_producto,cantidad,id_producto2,productos,monto_unit
0,1.0,Ana,1.0,2.0,1.0,Laptop,100.0
1,5.0,José,1.0,1.0,1.0,Laptop,100.0
2,6.0,Miguel,1.0,1.0,1.0,Laptop,100.0
3,2.0,Ana,2.0,1.0,2.0,Tablet,200.0
4,NaN,NaN,NaN,NaN,3.0,Smartphone,150.0
5,NaN,NaN,NaN,NaN,4.0,Monitor,300.0
6,3.0,María,5.0,3.0,NaN,NaN,NaN
7,4.0,Juan,6.0,2.0,NaN,NaN,NaN

In [2]:
import pandas as pd
#Crear datasets de ejemplo
productos_ejemplo = pd.DataFrame(
    {
    'id_producto2': [1, 2, 3, 4],
    'productos  ': ['Laptop', 'Tablet', 'Smartphone', 'Monitor'],
    'cantidad ': [10, 5, 8, 2], #Cantidades en inventario
    'monto_unit': [100, 200, 150, 300]
    }
)

ventas_ejemplo = pd.DataFrame(
    {
    'id_venta': [1, 2, 3, 4, 5, 6],
    'cliente': ['Ana', 'Ana', 'María', 'Juan', 'José', 'Miguel'],
    'id_producto': [1, 2, 5, 6, 1, 1],
    'cantidad ': [2, 1, 3, 2, 1, 1] #Cantidades vendidas
    }
)

pd.merge(
ventas_ejemplo, 
productos_ejemplo, 
how='inner',
left_on='id_producto',
right_on='id_producto2',
suffixes=('_ventas', '_inventario')
)

,id_venta,cliente,id_producto,cantidad _ventas,id_producto2,productos,cantidad _inventario,monto_unit
0,1,Ana,1,2,1,Laptop,10,100
1,2,Ana,2,1,2,Tablet,5,200
2,5,José,1,1,1,Laptop,10,100
3,6,Miguel,1,1,1,Laptop,10,100

### Uniones de tablas con Concat

In [8]:
#Crear dataframe de ejemplo: ventas de enero
df_enero = pd.DataFrame(
    {
    'fecha': ['2024-01-05', '2024-01-12', '2024-01-18', '2024-01-25'],
    'producto': ['Laptop', 'Mouse', 'Teclado', 'Monitor'],
    'cantidad': [2, 5, 3, 1],
    'total': [2400, 125, 255, 350]
    }
)
#Crear dataframe de ejemplo: ventas de enero
df_febrero = pd.DataFrame(
    {
    'fecha': ['2024-02-03', '2024-02-14', '2024-02-22'],
    'producto': ['Laptop', 'Auriculares', 'Mouse'],
    'cantidad': [1, 2, 3],
    'total': [1200, 130, 75]
    }
)
pd.concat([df_enero, df_febrero], ignore_index=True)

        fecha     producto  cantidad  total
0  2024-01-05       Laptop         2   2400
1  2024-01-12        Mouse         5    125
2  2024-01-18      Teclado         3    255
3  2024-01-25      Monitor         1    350
4  2024-02-03       Laptop         1   1200
5  2024-02-14  Auriculares         2    130
6  2024-02-22        Mouse         3     75

In [10]:
#Crear dataframes con diferentes columnas pero mismas filas
info_base = pd.DataFrame({
    'id_venta': [1, 2, 3, 4, 5],
    'producto': ['Laptop', 'Mouse', 'Teclado', 'Monitor', 'Webcam'],
    'total': [1200, 25, 85, 350, 45]
    })

info_adicional = pd.DataFrame({
    'region': ['Norte', 'Sur', 'Este', 'Oeste', 'Centro'],
    'vendedor': ['Ana García', 'Carlos Méndez', 'María López', 'Juan Pérez', 'Lucía Rodríguez'],
    'estado': ['Completado', 'Pendiente', 'Completado', 'Completado', 'Cancelado']
    }) 

pd.concat([info_base, info_adicional], axis=1)

   id_venta producto  total  region         vendedor      estado
0         1   Laptop   1200   Norte       Ana García  Completado
1         2    Mouse     25     Sur    Carlos Méndez   Pendiente
2         3  Teclado     85    Este      María López  Completado
3         4  Monitor    350   Oeste       Juan Pérez  Completado
4         5   Webcam     45  Centro  Lucía Rodríguez   Cancelado