<h1 align="center">Limpieza y preparación de datos</h1>

## U3.01 – Detección e Identificación de Problemas en los Datos

### Cargar e inspeccionar datos iniciales

In [273]:
import pandas as pd
import numpy as np

# Crear un DataFrame “sucio” de ejemplo
df = pd.DataFrame({
    'id_cliente': [1, 2, 2, 3, 4, 5, 6, 6, None],
    'nombre': [' Ana  ', 'CARLOS', 'CARLOS', 'María', None, 'Juan', 'Lucia', 'Lucia', 'Ana'],
    'edad': [25, 40, 40, None, 17, 80, 35, 35, 25],
    'ingresos_mensuales': [1500.0, 2500.50, 2500.50, 3200.0, 500.0, None, 1800.0, 1800.0, 1500.0],
    'ciudad': ['Madrid', 'Barcelona', 'Barcelona', 'Madrid', 'MADRID', 'Valencia', 'Barcelona', 'Barcelona', 'Madrid'],
    'segmento': ['Silv', 'Gol', 'Gol', 'Premiu', 'Desconocido', None, 'God', 'Gold', 'silver'],
    'fecha_registro': ['2024-01-10', '2024/02/15', '2024/02/15', '10-03-2024',
                       '2024-04-01', '2024-04-05', '2024-04-28', np.nan, '2024-05-10'],
    'score_riesgo': [0.1, 0.3, 0.3, 0.95, -0.2, 1.5, 0.5, 0.5, 0.1]
})

# Vista rápida
df

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo
0,1.0,Ana,25.0,1500.0,Madrid,Silv,2024-01-10,0.10
1,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.30
2,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.30
3,3.0,María,NaN,3200.0,Madrid,Premiu,10-03-2024,0.95
4,4.0,NaN,17.0,500.0,MADRID,Desconocido,2024-04-01,-0.20
5,5.0,Juan,80.0,NaN,Valencia,NaN,2024-04-05,1.50
6,6.0,Lucia,35.0,1800.0,Barcelona,God,2024-04-28,0.50
7,6.0,Lucia,35.0,1800.0,Barcelona,Gold,NaN,0.50
8,NaN,Ana,25.0,1500.0,Madrid,silver,2024-05-10,0.10

Problemas intencionales:

- Valores faltantes en nombre, edad, ingresos_mensuales, id_cliente, fecha_registro, segmento

- Duplicados (id_cliente 2 y 6)

- Inconsistencias de texto ("Madrid" vs "MADRID", "Silv" vs "silver")

- Fechas con formato mixto

- Posibles outliers: edad 17 y 80, score_riesgo -0.2 y 1.5

### Identificación de Valores Faltantes

In [315]:
#Contar valores faltantes por columna
df.isna().sum()

id_cliente                 1
nombre                     1
edad                       1
ingresos_mensuales         1
ciudad                     0
segmento                   1
fecha_registro             1
score_riesgo               0
nombre_limpio              1
nombre vs nombre_limpio    1
nombre_mayusc              1
segmento_norm              1
genero                     0
fecha_registro_dt          1
fecha_iso                  1
anio                       1
mes                        1
dia                        1
trimestre                  1
numero_semana              1
numero_semana_año          1
dia_semana                 1
id_cliente_int             1
dtype: int64

In [351]:
(df.isna().mean()*100).round(2)

id_cliente                 11.11
nombre                     11.11
edad                       11.11
ingresos_mensuales         11.11
ciudad                      0.00
segmento                   11.11
fecha_registro             11.11
score_riesgo                0.00
nombre_limpio              11.11
nombre vs nombre_limpio    11.11
nombre_mayusc              11.11
segmento_norm              11.11
genero                      0.00
fecha_registro_dt          11.11
fecha_iso                  11.11
anio                       11.11
mes                        11.11
dia                        11.11
trimestre                  11.11
numero_semana              11.11
numero_semana_año          11.11
dia_semana                 11.11
id_cliente_int             11.11
dtype: float64

### Identificación de Duplicados

In [386]:
# Detectar filas completamente duplicadas
df[df.duplicated(keep=False)]

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
1,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.3,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
2,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.3,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2

In [420]:
df[df.duplicated(keep=False, subset=['id_cliente'])]

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
1,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.3,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
2,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.3,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
6,6.0,Lucia,35.0,1800.0,Barcelona,God,2024-04-28,0.5,Lucia,5.0 vs 5.0,...,2024-04-28,2024-04-28,2024.0,4.0,28.0,2.0,7,17,Domingo,6
7,6.0,Lucia,35.0,1800.0,Barcelona,Gold,NaN,0.5,Lucia,5.0 vs 5.0,...,NaT,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,6

In [421]:
# Contar registros por ID Cliente
df['id_cliente'].value_counts()

id_cliente
2.0    2
6.0    2
1.0    1
3.0    1
4.0    1
5.0    1
Name: count, dtype: int64

### Detección de Inconsistencias de Formato

In [422]:
df.dtypes

id_cliente                        float64
nombre                                str
edad                              float64
ingresos_mensuales                float64
ciudad                                str
segmento                              str
fecha_registro                        str
score_riesgo                      float64
nombre_limpio                         str
nombre vs nombre_limpio               str
nombre_mayusc                         str
segmento_norm                         str
genero                                str
fecha_registro_dt          datetime64[us]
fecha_iso                             str
anio                              float64
mes                               float64
dia                               float64
trimestre                         float64
numero_semana                      UInt32
numero_semana_año                  UInt32
dia_semana                            str
id_cliente_int                      Int64
dtype: object

In [423]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id_cliente               8 non-null      float64
 1   nombre                   8 non-null      str
 2   edad                     8 non-null      float64
 3   ingresos_mensuales       8 non-null      float64
 4   ciudad                   9 non-null      str
 5   segmento                 8 non-null      str
 6   fecha_registro           8 non-null      str
 7   score_riesgo             9 non-null      float64
 8   nombre_limpio            8 non-null      str
 9   nombre vs nombre_limpio  8 non-null      str
 10  nombre_mayusc            8 non-null      str
 11  segmento_norm            8 non-null      str
 12  genero                   9 non-null      str
 13  fecha_registro_dt        8 non-null      datetime64[us]
 14  fecha_iso                8 non-null      str
 15  anio                     8 non-null      float64
 16  mes                      8 non-null      float64
 17  dia                      8 non-null      float64
 18  trimestre                8 non-null      float64
 19  numero_semana            8 non-null      UInt32
 20  numero_semana_año        8 non-null      UInt32
 21  dia_semana               8 non-null      str
 22  id_cliente_int           8 non-null      Int64
dtypes: Int64(1), UInt32(2), datetime64[us](1), float64(8), str(11)
memory usage: 1.7 KB

In [424]:
# Analizar inconsistencias en las columnas categoricas
for col in df.select_dtypes(include='str').columns.sort_values():
    print(f'{col}: {list(df[col].unique())}')
    print(f'-' * 150)

ciudad: ['Madrid', 'Barcelona', 'MADRID', 'Valencia']
------------------------------------------------------------------------------------------------------------------------------------------------------
dia_semana: ['Martes', 'Jueves', 'Domingo', 'Sábado', nan]
------------------------------------------------------------------------------------------------------------------------------------------------------
fecha_iso: ['2024-10-01', '2024-02-15', '2024-03-10', '2024-01-04', '2024-05-04', '2024-04-28', nan, '2024-10-05']
------------------------------------------------------------------------------------------------------------------------------------------------------
fecha_registro: ['2024-01-10', '2024/02/15', '10-03-2024', '2024-04-01', '2024-04-05', '2024-04-28', nan, '2024-05-10']
------------------------------------------------------------------------------------------------------------------------------------------------------
genero: ['female', 'male', 'mostly_female', 'unknown']
------------------------------------------------------------------------------------------------------------------------------------------------------
nombre: [' Ana  ', 'CARLOS', 'María', nan, 'Juan', 'Lucia', 'Ana']
------------------------------------------------------------------------------------------------------------------------------------------------------
nombre vs nombre_limpio: ['6.0 vs 3.0', '6.0 vs 6.0', '5.0 vs 5.0', nan, '4.0 vs 4.0', '3.0 vs 3.0']
------------------------------------------------------------------------------------------------------------------------------------------------------
nombre_limpio: ['Ana', 'Carlos', 'María', nan, 'Juan', 'Lucia']
------------------------------------------------------------------------------------------------------------------------------------------------------
nombre_mayusc: ['ANA', 'CARLOS', 'MARÍA', nan, 'JUAN', 'LUCIA']
------------------------------------------------------------------------------------------------------------------------------------------------------
segmento: ['Silv', 'Gol', 'Premiu', 'Desconocido', nan, 'God', 'Gold', 'silver']
------------------------------------------------------------------------------------------------------------------------------------------------------
segmento_norm: ['Silver', 'Gold', 'Premium', 'Desconocido', nan]
------------------------------------------------------------------------------------------------------------------------------------------------------

### Detección de Valores Atípicos (outliers) y Fuera de Rango

In [425]:
# Usar describe para ver posibles valores extremos
df.describe()

,id_cliente,edad,ingresos_mensuales,score_riesgo,fecha_registro_dt,anio,mes,dia,trimestre,numero_semana,numero_semana_año,id_cliente_int
count,8.00000,8.000000,8.0000,9.000000,8,8.0,8.000000,8.000000,8.000000,8.0,8.0,8.0
mean,3.62500,37.125000,1912.6250,0.450000,2024-04-29 12:00:00,2024.0,4.625000,10.250000,2.000000,5.0,17.5,3.625
min,1.00000,17.000000,500.0000,-0.200000,2024-01-04 00:00:00,2024.0,1.000000,1.000000,1.000000,2.0,1.0,1.0
25%,2.00000,25.000000,1500.0000,0.100000,2024-02-15 00:00:00,2024.0,2.000000,4.000000,1.000000,4.0,7.0,2.0
50%,3.50000,35.000000,1800.0000,0.300000,2024-04-03 12:00:00,2024.0,3.500000,7.500000,1.500000,5.0,13.5,3.5
75%,5.25000,40.000000,2500.5000,0.500000,2024-06-10 12:00:00,2024.0,6.250000,15.000000,2.500000,6.25,23.5,5.25
max,6.00000,80.000000,3200.0000,1.500000,2024-10-05 00:00:00,2024.0,10.000000,28.000000,4.000000,7.0,40.0,6.0
std,1.92261,19.134393,820.2722,0.508675,NaN,0.0,3.543102,8.876132,1.309307,1.772811,14.937967,1.92261

In [426]:
q1 = df['edad'].quantile(0.25)
q3 = df['edad'].quantile(0.75)

iqr = q3 - q1
lim_inf = q1 - 1.5 * iqr
lim_sup = q3 + 1.5 * iqr
outliers = df[(df['edad'] < lim_inf) | (df['edad'] > lim_sup)]
print(f'limites teóricos: {lim_inf}, {lim_sup}')
outliers

limites teóricos: 2.5, 62.5

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
5,5.0,Juan,80.0,NaN,Valencia,NaN,2024-04-05,1.5,Juan,4.0 vs 4.0,...,2024-05-04,2024-05-04,2024.0,5.0,4.0,2.0,6,18,Sábado,5

In [427]:
outliers_score = df[(df['score_riesgo'] < 0) | (df['score_riesgo'] > 1)]
outliers_score

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
4,4.0,NaN,17.0,500.0,MADRID,Desconocido,2024-04-01,-0.2,NaN,NaN,...,2024-01-04,2024-01-04,2024.0,1.0,4.0,1.0,4,1,Jueves,4
5,5.0,Juan,80.0,NaN,Valencia,NaN,2024-04-05,1.5,Juan,4.0 vs 4.0,...,2024-05-04,2024-05-04,2024.0,5.0,4.0,2.0,6,18,Sábado,5

## U3.02 – Tratamiento de datos faltantes.

Estrategias: eliminar vs imputar

- Eliminar filas/columnas cuando:

    - El porcentaje de nulos es muy alto

    - La fila está casi vacía

- Imputar (rellenar) cuando:

    - La columna es importante

    - Se puede estimar un valor razonable (media, mediana, moda, reglas de negocio)

### Eliminación de filas completas

In [428]:
df

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
0,1.0,Ana,25.0,1500.0,Madrid,Silv,2024-01-10,0.10,Ana,6.0 vs 3.0,...,2024-10-01,2024-10-01,2024.0,10.0,1.0,4.0,2,40,Martes,1
1,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.30,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
2,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.30,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
3,3.0,María,NaN,3200.0,Madrid,Premiu,10-03-2024,0.95,María,5.0 vs 5.0,...,2024-03-10,2024-03-10,2024.0,3.0,10.0,1.0,7,10,Domingo,3
4,4.0,NaN,17.0,500.0,MADRID,Desconocido,2024-04-01,-0.20,NaN,NaN,...,2024-01-04,2024-01-04,2024.0,1.0,4.0,1.0,4,1,Jueves,4
5,5.0,Juan,80.0,NaN,Valencia,NaN,2024-04-05,1.50,Juan,4.0 vs 4.0,...,2024-05-04,2024-05-04,2024.0,5.0,4.0,2.0,6,18,Sábado,5
6,6.0,Lucia,35.0,1800.0,Barcelona,God,2024-04-28,0.50,Lucia,5.0 vs 5.0,...,2024-04-28,2024-04-28,2024.0,4.0,28.0,2.0,7,17,Domingo,6
7,6.0,Lucia,35.0,1800.0,Barcelona,Gold,NaN,0.50,Lucia,5.0 vs 5.0,...,NaT,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,6
8,NaN,Ana,25.0,1500.0,Madrid,silver,2024-05-10,0.10,Ana,3.0 vs 3.0,...,2024-10-05,2024-10-05,2024.0,10.0,5.0,4.0,6,40,Sábado,<NA>

In [429]:
df_sin_nulos = df.dropna()
df_sin_nulos

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
0,1.0,Ana,25.0,1500.0,Madrid,Silv,2024-01-10,0.1,Ana,6.0 vs 3.0,...,2024-10-01,2024-10-01,2024.0,10.0,1.0,4.0,2,40,Martes,1
1,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.3,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
2,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.3,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
6,6.0,Lucia,35.0,1800.0,Barcelona,God,2024-04-28,0.5,Lucia,5.0 vs 5.0,...,2024-04-28,2024-04-28,2024.0,4.0,28.0,2.0,7,17,Domingo,6

In [430]:
df_id_nulos = df.dropna(subset=['id_cliente'])
df_id_nulos

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
0,1.0,Ana,25.0,1500.0,Madrid,Silv,2024-01-10,0.10,Ana,6.0 vs 3.0,...,2024-10-01,2024-10-01,2024.0,10.0,1.0,4.0,2,40,Martes,1
1,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.30,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
2,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.30,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
3,3.0,María,NaN,3200.0,Madrid,Premiu,10-03-2024,0.95,María,5.0 vs 5.0,...,2024-03-10,2024-03-10,2024.0,3.0,10.0,1.0,7,10,Domingo,3
4,4.0,NaN,17.0,500.0,MADRID,Desconocido,2024-04-01,-0.20,NaN,NaN,...,2024-01-04,2024-01-04,2024.0,1.0,4.0,1.0,4,1,Jueves,4
5,5.0,Juan,80.0,NaN,Valencia,NaN,2024-04-05,1.50,Juan,4.0 vs 4.0,...,2024-05-04,2024-05-04,2024.0,5.0,4.0,2.0,6,18,Sábado,5
6,6.0,Lucia,35.0,1800.0,Barcelona,God,2024-04-28,0.50,Lucia,5.0 vs 5.0,...,2024-04-28,2024-04-28,2024.0,4.0,28.0,2.0,7,17,Domingo,6
7,6.0,Lucia,35.0,1800.0,Barcelona,Gold,NaN,0.50,Lucia,5.0 vs 5.0,...,NaT,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,6

### Imputación de datos.

In [431]:
# Calcular media y mediana de edad

promedio_edad = df['edad'].mean()
mediana_edad = df['edad'].median()

df['edad_fill'] = df['edad'].fillna(mediana_edad)
df[['edad', 'edad_fill']]

   edad  edad_fill
0  25.0       25.0
1  40.0       40.0
2  40.0       40.0
3   NaN       35.0
4  17.0       17.0
5  80.0       80.0
6  35.0       35.0
7  35.0       35.0
8  25.0       25.0

In [432]:
promedio_edad = df['edad'].mean()
mediana_edad = df['edad'].median()

# Imputación con mediana
df['edad_fill'] = df['edad'].fillna(mediana_edad)

#Forward fill: Propagar último valor hacia adelante
df['fecha_registro_ffill'] = df['fecha_registro'].ffill()

#backward fill: propagar próximo valor hacia atrás
df['fecha_registro_bfill'] = df['fecha_registro'].bfill()

#Estrategia para 'segmento': reemplazar None por 'Desconocido'
df['segmento_fill'] = df['segmento'].fillna('Desconocido')

df[['edad', 'edad_fill', 'fecha_registro', 'fecha_registro_ffill', 'fecha_registro_bfill','segmento','segmento_fill']]

,edad,edad_fill,fecha_registro,fecha_registro_ffill,fecha_registro_bfill,segmento,segmento_fill
0,25.0,25.0,2024-01-10,2024-01-10,2024-01-10,Silv,Silv
1,40.0,40.0,2024/02/15,2024/02/15,2024/02/15,Gol,Gol
2,40.0,40.0,2024/02/15,2024/02/15,2024/02/15,Gol,Gol
3,NaN,35.0,10-03-2024,10-03-2024,10-03-2024,Premiu,Premiu
4,17.0,17.0,2024-04-01,2024-04-01,2024-04-01,Desconocido,Desconocido
5,80.0,80.0,2024-04-05,2024-04-05,2024-04-05,NaN,Desconocido
6,35.0,35.0,2024-04-28,2024-04-28,2024-04-28,God,God
7,35.0,35.0,NaN,2024-04-28,2024-05-10,Gold,Gold
8,25.0,25.0,2024-05-10,2024-05-10,2024-05-10,silver,silver

## U3.03 – Normalización de Texto y Categorías

### Limpiar y normalizar texto

In [433]:
df = pd.DataFrame({
    'id_cliente': [1, 2, 2, 3, 4, 5, 6, 6, None],
    'nombre': [' Ana  ', 'CARLOS', 'CARLOS', 'María', None, 'Juan', 'Lucia', 'Lucia', 'Ana'],
    'edad': [25, 40, 40, None, 17, 80, 35, 35, 25],
    'ingresos_mensuales': [1500.0, 2500.50, 2500.50, 3200.0, 500.0, None, 1800.0, 1800.0, 1500.0],
    'ciudad': ['Madrid', 'Barcelona', 'Barcelona', 'Madrid', 'MADRID', 'Valencia', 'Barcelona', 'Barcelona', 'Madrid'],
    'segmento': ['Silv', 'Gol', 'Gol', 'Premiu', 'Desconocido', None, 'God', 'Gold', 'silver'],
    'fecha_registro': ['2024-01-10', '2024/02/15', '2024/02/15', '10-03-2024',
                       '2024-04-01', '2024-04-05', '2024-04-28', np.nan, '2024-05-10'],
    'score_riesgo': [0.1, 0.3, 0.3, 0.95, -0.2, 1.5, 0.5, 0.5, 0.1]
})

df['nombre_limpio']=df['nombre'].str.strip().str.title()
df['nombre vs nombre_limpio']=df['nombre'].str.len().astype(str) + ' vs ' + df['nombre_limpio'].str.len().astype(str)
#Convertir a mayúsculas
df['nombre_mayusc']= (df['nombre'].str.upper().str.strip())
df[['nombre', 'nombre_limpio', 'nombre vs nombre_limpio', 'nombre_mayusc']]

   nombre nombre_limpio nombre vs nombre_limpio nombre_mayusc
0   Ana             Ana              6.0 vs 3.0           ANA
1  CARLOS        Carlos              6.0 vs 6.0        CARLOS
2  CARLOS        Carlos              6.0 vs 6.0        CARLOS
3   María         María              5.0 vs 5.0         MARÍA
4     NaN           NaN                     NaN           NaN
5    Juan          Juan              4.0 vs 4.0          JUAN
6   Lucia         Lucia              5.0 vs 5.0         LUCIA
7   Lucia         Lucia              5.0 vs 5.0         LUCIA
8     Ana           Ana              3.0 vs 3.0           ANA

### Normalización de Categorías

In [434]:
list(df['segmento'].unique())

['Silv', 'Gol', 'Premiu', 'Desconocido', nan, 'God', 'Gold', 'silver']

In [435]:
map_segmento={
    'Silv': 'Silver',
    'Gol': 'Gold',
    'God': 'Gold',
    'Premiu': 'Premium', 
}
df['segmento_norm']= df['segmento'].replace(map_segmento).str.capitalize()
df[['segmento', 'segmento_norm']]

      segmento segmento_norm
0         Silv        Silver
1          Gol          Gold
2          Gol          Gold
3       Premiu       Premium
4  Desconocido   Desconocido
5          NaN           NaN
6          God          Gold
7         Gold          Gold
8       silver        Silver

### Detección y Limpieza de Patrones Específicos

In [436]:
# %pip install gender-guesser

In [437]:
import gender_guesser.detector as gender
d= gender.Detector()

df['genero']= df['nombre_limpio'].apply(lambda x: d.get_gender(x))
df[['nombre_limpio', 'genero']]

  nombre_limpio         genero
0           Ana         female
1        Carlos           male
2        Carlos           male
3         María  mostly_female
4           NaN        unknown
5          Juan           male
6         Lucia         female
7         Lucia         female
8           Ana         female

## 3.04 Transformación y Estandarización de Fechas

### Conversión de Formatos de Fecha

In [438]:
df['fecha_registro_dt']= pd.to_datetime(df['fecha_registro'], errors='coerce', format='mixed', dayfirst=True)
df['fecha_iso']= df['fecha_registro_dt'].dt.strftime('%Y-%m-%d')
df[['fecha_registro', 'fecha_registro_dt', 'fecha_iso']]

  fecha_registro fecha_registro_dt   fecha_iso
0     2024-01-10        2024-10-01  2024-10-01
1     2024/02/15        2024-02-15  2024-02-15
2     2024/02/15        2024-02-15  2024-02-15
3     10-03-2024        2024-03-10  2024-03-10
4     2024-04-01        2024-01-04  2024-01-04
5     2024-04-05        2024-05-04  2024-05-04
6     2024-04-28        2024-04-28  2024-04-28
7            NaN               NaT         NaN
8     2024-05-10        2024-10-05  2024-10-05

### Extracción de componentes de fecha

In [439]:
#Extraer componentes de fecha
df['anio']  = df['fecha_registro_dt'].dt.year
df['mes']  = df['fecha_registro_dt'].dt.month
df['dia']  = df['fecha_registro_dt'].dt.day
df['trimestre']  = df['fecha_registro_dt'].dt.quarter
df['numero_semana']  = df['fecha_registro_dt'].dt.isocalendar().day
df['numero_semana_año']  = df['fecha_registro_dt'].dt.isocalendar().week
df['dia_semana']  = df['fecha_registro_dt'].dt.day_name(locale='es_ES')

df[['fecha_registro_dt', 'anio', 'mes', 'dia', 'trimestre', 'dia_semana', 'numero_semana', 'numero_semana_año']]

,fecha_registro_dt,anio,mes,dia,trimestre,dia_semana,numero_semana,numero_semana_año
0,2024-10-01,2024.0,10.0,1.0,4.0,Martes,2,40
1,2024-02-15,2024.0,2.0,15.0,1.0,Jueves,4,7
2,2024-02-15,2024.0,2.0,15.0,1.0,Jueves,4,7
3,2024-03-10,2024.0,3.0,10.0,1.0,Domingo,7,10
4,2024-01-04,2024.0,1.0,4.0,1.0,Jueves,4,1
5,2024-05-04,2024.0,5.0,4.0,2.0,Sábado,6,18
6,2024-04-28,2024.0,4.0,28.0,2.0,Domingo,7,17
7,NaT,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
8,2024-10-05,2024.0,10.0,5.0,4.0,Sábado,6,40

### Conversión de Tipos de Datos

In [440]:
df.dtypes

id_cliente                        float64
nombre                                str
edad                              float64
ingresos_mensuales                float64
ciudad                                str
segmento                              str
fecha_registro                        str
score_riesgo                      float64
nombre_limpio                         str
nombre vs nombre_limpio               str
nombre_mayusc                         str
segmento_norm                         str
genero                                str
fecha_registro_dt          datetime64[us]
fecha_iso                             str
anio                              float64
mes                               float64
dia                               float64
trimestre                         float64
numero_semana                      UInt32
numero_semana_año                  UInt32
dia_semana                            str
dtype: object

In [441]:
df['id_cliente_int'] = df['id_cliente'].astype('Int64')
df['id_cliente_int']

0       1
1       2
2       2
3       3
4       4
5       5
6       6
7       6
8    <NA>
Name: id_cliente_int, dtype: Int64

## U3.05 – Consolidación Final - Tratamiento de Duplicados y Validación

### Eliminación de Duplicados Exactos

In [453]:
#Eliminar duplicados exactos
df_sin_duplicados_completos = df.drop_duplicates()
df_sin_duplicados_completos

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
0,1.0,Ana,25.0,1500.0,Madrid,Silv,2024-01-10,0.10,Ana,6.0 vs 3.0,...,2024-10-01,2024-10-01,2024.0,10.0,1.0,4.0,2,40,Martes,1
1,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.30,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
3,3.0,María,NaN,3200.0,Madrid,Premiu,10-03-2024,0.95,María,5.0 vs 5.0,...,2024-03-10,2024-03-10,2024.0,3.0,10.0,1.0,7,10,Domingo,3
4,4.0,NaN,17.0,500.0,MADRID,Desconocido,2024-04-01,-0.20,NaN,NaN,...,2024-01-04,2024-01-04,2024.0,1.0,4.0,1.0,4,1,Jueves,4
5,5.0,Juan,80.0,NaN,Valencia,NaN,2024-04-05,1.50,Juan,4.0 vs 4.0,...,2024-05-04,2024-05-04,2024.0,5.0,4.0,2.0,6,18,Sábado,5
6,6.0,Lucia,35.0,1800.0,Barcelona,God,2024-04-28,0.50,Lucia,5.0 vs 5.0,...,2024-04-28,2024-04-28,2024.0,4.0,28.0,2.0,7,17,Domingo,6
7,6.0,Lucia,35.0,1800.0,Barcelona,Gold,NaN,0.50,Lucia,5.0 vs 5.0,...,NaT,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,NaN,6
8,NaN,Ana,25.0,1500.0,Madrid,silver,2024-05-10,0.10,Ana,3.0 vs 3.0,...,2024-10-05,2024-10-05,2024.0,10.0,5.0,4.0,6,40,Sábado,<NA>

### Eliminación de Duplicados por columnas

In [454]:
# Duplicados por id_cliente (conservar primera ocurrencia)
df_sin_duplicados_id = df.drop_duplicates(subset=['id_cliente'], keep='first')
df_sin_duplicados_id

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
0,1.0,Ana,25.0,1500.0,Madrid,Silv,2024-01-10,0.10,Ana,6.0 vs 3.0,...,2024-10-01,2024-10-01,2024.0,10.0,1.0,4.0,2,40,Martes,1
1,2.0,CARLOS,40.0,2500.5,Barcelona,Gol,2024/02/15,0.30,Carlos,6.0 vs 6.0,...,2024-02-15,2024-02-15,2024.0,2.0,15.0,1.0,4,7,Jueves,2
3,3.0,María,NaN,3200.0,Madrid,Premiu,10-03-2024,0.95,María,5.0 vs 5.0,...,2024-03-10,2024-03-10,2024.0,3.0,10.0,1.0,7,10,Domingo,3
4,4.0,NaN,17.0,500.0,MADRID,Desconocido,2024-04-01,-0.20,NaN,NaN,...,2024-01-04,2024-01-04,2024.0,1.0,4.0,1.0,4,1,Jueves,4
5,5.0,Juan,80.0,NaN,Valencia,NaN,2024-04-05,1.50,Juan,4.0 vs 4.0,...,2024-05-04,2024-05-04,2024.0,5.0,4.0,2.0,6,18,Sábado,5
6,6.0,Lucia,35.0,1800.0,Barcelona,God,2024-04-28,0.50,Lucia,5.0 vs 5.0,...,2024-04-28,2024-04-28,2024.0,4.0,28.0,2.0,7,17,Domingo,6
8,NaN,Ana,25.0,1500.0,Madrid,silver,2024-05-10,0.10,Ana,3.0 vs 3.0,...,2024-10-05,2024-10-05,2024.0,10.0,5.0,4.0,6,40,Sábado,<NA>

### Validación básica de calidad

In [455]:
df.dtypes

id_cliente                        float64
nombre                                str
edad                              float64
ingresos_mensuales                float64
ciudad                                str
segmento                              str
fecha_registro                        str
score_riesgo                      float64
nombre_limpio                         str
nombre vs nombre_limpio               str
nombre_mayusc                         str
segmento_norm                         str
genero                                str
fecha_registro_dt          datetime64[us]
fecha_iso                             str
anio                              float64
mes                               float64
dia                               float64
trimestre                         float64
numero_semana                      UInt32
numero_semana_año                  UInt32
dia_semana                            str
id_cliente_int                      Int64
dtype: object

In [456]:
# Validación: Rango de valores

print(f"Edad: min={df['edad'].min()}, máx={df['edad'].max()}")
print(f"Score riesgo: min={df['score_riesgo'].min()}, máx={df['score_riesgo'].max()}")

edades_invalidas = df[(df['edad'] < 18) | (df['edad'] > 100)]
print(f"Edades fuera de rango [18, 100]: {len(edades_invalidas)} (Requiere revisión)")
edades_invalidas

Edad: min=17.0, máx=80.0
Score riesgo: min=-0.2, máx=1.5
Edades fuera de rango [18, 100]: 1 (Requiere revisión)

,id_cliente,nombre,edad,ingresos_mensuales,ciudad,segmento,fecha_registro,score_riesgo,nombre_limpio,nombre vs nombre_limpio,...,fecha_registro_dt,fecha_iso,anio,mes,dia,trimestre,numero_semana,numero_semana_año,dia_semana,id_cliente_int
4,4.0,NaN,17.0,500.0,MADRID,Desconocido,2024-04-01,-0.2,NaN,NaN,...,2024-01-04,2024-01-04,2024.0,1.0,4.0,1.0,4,1,Jueves,4

In [457]:
# Validación: Valores faltantes residuales
print("\nValidación: Valores faltantes residuales")
faltantes = df.isna().sum()
print(faltantes[faltantes > 0])
print("(Faltantes permisibles: fecha_registro opriginal puede tener NaN)")

Validación: Valores faltantes residuales
id_cliente                 1
nombre                     1
edad                       1
ingresos_mensuales         1
segmento                   1
fecha_registro             1
nombre_limpio              1
nombre vs nombre_limpio    1
nombre_mayusc              1
segmento_norm              1
fecha_registro_dt          1
fecha_iso                  1
anio                       1
mes                        1
dia                        1
trimestre                  1
numero_semana              1
numero_semana_año          1
dia_semana                 1
id_cliente_int             1
dtype: int64
(Faltantes permisibles: fecha_registro opriginal puede tener NaN)

In [458]:
# Validación: Unicidad de ID
print("\nValidación: Unicidad de identificadores")
print(f"Total de registros: {len(df)}")
print(f"IDs únicos: {df['id_cliente'].nunique()}")
if len(df) == df['id_cliente'].nunique():
    print("VALIDADO: Cada registro tiene ID único")
else:
    print("ERROR: Existen IDs duplicados")

Validación: Unicidad de identificadores
Total de registros: 9
IDs únicos: 6
ERROR: Existen IDs duplicados

In [459]:
# Validación: Valores válidos en categorías 
print("\nValidación: Valores válidos en categorías") 
segmentos_validos = {'Silver', 'Gold', 'Premium', 'Desconocido'} 
segmentos_actuales = set(df['segmento_norm'].dropna().unique()) 
print(f"Segmentos válidos esperados: {segmentos_validos}") 
print(f"Segmentos encontrados: {segmentos_actuales}") 
if segmentos_actuales.issubset(segmentos_validos): 
    print("✓ VALIDADO: Todas las categorías son válidas") 
else: print(f"✗ ERROR: Categorías no válidas encontradas: {segmentos_actuales - segmentos_validos}")

Validación: Valores válidos en categorías
Segmentos válidos esperados: {'Gold', 'Silver', 'Premium', 'Desconocido'}
Segmentos encontrados: {'Gold', 'Premium', 'Silver', 'Desconocido'}
✓ VALIDADO: Todas las categorías son válidas

In [460]:
# Resumen de limpieza
print("\n=== RESUMEN DE LIMPIEZA ===") 
print(f"Dataset original: {len(df)} filas") 
print(f"Dataset limpio: {len(df)} filas") 
print(f"Filas eliminadas: {len(df) - len(df)} ({((len(df) - len(df)) / len(df) * 100):.1f}%)")

=== RESUMEN DE LIMPIEZA ===
Dataset original: 9 filas
Dataset limpio: 9 filas
Filas eliminadas: 0 (0.0%)

In [461]:
# Resumen de limpieza
print("\n=== RESUMEN DE LIMPIEZA ===") 
print(f"Dataset original: {len(df)} filas") 
print(f"Dataset limpio: {len(df_sin_duplicados_completos)} filas") 
print(f"Filas eliminadas: {len(df) - len(df_sin_duplicados_completos)} ({((len(df) - len(df_sin_duplicados_completos)) / len(df) * 100):.1f}%)")

=== RESUMEN DE LIMPIEZA ===
Dataset original: 9 filas
Dataset limpio: 8 filas
Filas eliminadas: 1 (11.1%)

In [464]:
list (df.columns)

['id_cliente',
 'nombre',
 'edad',
 'ingresos_mensuales',
 'ciudad',
 'segmento',
 'fecha_registro',
 'score_riesgo',
 'nombre_limpio',
 'nombre vs nombre_limpio',
 'nombre_mayusc',
 'segmento_norm',
 'genero',
 'fecha_registro_dt',
 'fecha_iso',
 'anio',
 'mes',
 'dia',
 'trimestre',
 'numero_semana',
 'numero_semana_año',
 'dia_semana',
 'id_cliente_int']

### Exportar Dataset Final Limpio

In [466]:
# Consultar columnas finales 
list (df.columns) 
# Seleccionar columnas finales 
columnas_relevantes = ['id_cliente_int', 
'nombre_limpio', 
'edad', 
'segmento_norm', 
'ingresos_mensuales', 
'ciudad', 
'fecha_registro_dt', 
'anio',
'mes',
'dia',
'dia_semana',
'score_riesgo'
]
df_final = df[columnas_relevantes].copy()
df_final

,id_cliente_int,nombre_limpio,edad,segmento_norm,ingresos_mensuales,ciudad,fecha_registro_dt,anio,mes,dia,dia_semana,score_riesgo
0,1,Ana,25.0,Silver,1500.0,Madrid,2024-10-01,2024.0,10.0,1.0,Martes,0.10
1,2,Carlos,40.0,Gold,2500.5,Barcelona,2024-02-15,2024.0,2.0,15.0,Jueves,0.30
2,2,Carlos,40.0,Gold,2500.5,Barcelona,2024-02-15,2024.0,2.0,15.0,Jueves,0.30
3,3,María,NaN,Premium,3200.0,Madrid,2024-03-10,2024.0,3.0,10.0,Domingo,0.95
4,4,NaN,17.0,Desconocido,500.0,MADRID,2024-01-04,2024.0,1.0,4.0,Jueves,-0.20
5,5,Juan,80.0,NaN,NaN,Valencia,2024-05-04,2024.0,5.0,4.0,Sábado,1.50
6,6,Lucia,35.0,Gold,1800.0,Barcelona,2024-04-28,2024.0,4.0,28.0,Domingo,0.50
7,6,Lucia,35.0,Gold,1800.0,Barcelona,NaT,NaN,NaN,NaN,NaN,0.50
8,<NA>,Ana,25.0,Silver,1500.0,Madrid,2024-10-05,2024.0,10.0,5.0,Sábado,0.10

In [467]:
# Renombrar columnas 
df_final = df[columnas_relevantes].rename(columns={ 
'id_cliente_int': 'id_cliente', 
'edad': 'edad', 
'nombre_limpio': 'nombre',
'segmento_norm': 'segmento', 
'fecha_registro_dt': 'fecha_registro' }) 
# Exportar resultados limpios 
df_final.to_csv('clientes_limpios.csv', index=False, encoding='utf-8') 
print("✅ Dataset limpio guardado como 'clientes_limpio.csv'")

✅ Dataset limpio guardado como 'clientes_limpio.csv'